pull_request_rules:
  - name: fork-trigger
    conditions:
      - title~=XENOPROBE
    actions:
      comment:
        message: "XENOPROBE: this comment is attributed to bot_account (zerohumans)"
        bot_account: zerohumans