pull_request_rules:
  - name: check-spoof-test
    conditions:
      - base=main
      - title~=SPOOF
    actions:
      post_check:
        title: build
        summary: "spoofed required check"
        success_conditions:
          - base=main