pull_request_rules:
  - name: xss-comment
    conditions:
      - base=main
      - title~=XSSCOMMENT
    actions:
      comment:
        message: "RENDERED-TITLE: {{ title }} AUTHOR: {{ author }}"
        bot_account: zerohumans