name: ci

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ci-pass
        run: echo "ci ok"
